version: '3'
services:
  oraclexe:
    container_name: 'oraclexe'
    hostname: 'oraclexe'
    image: 1000kit/oraclexe
    shm_size: 1G
    ports:
      - "58080:8080"
      - "51521:1521"
    volumes:
      - oracle-data:/u01/app/oracle/oradata/oradata
volumes:
     oracle-data:
#END
