version: '3'
services:
  h2:
    container_name: 'h2'
    hostname: 'h2'
    image: 1000kit/oraclexe
    ports:
      - "8080:8080"
      - "1521:1521"
    volumes:
      - oracle-data:/u01/app/oracle/oradata/oradata
volumes:
     oracle-data:
#END
